### ISSUE TITLE
Select events

### ISSUE THREAD

**Issue by BrockReece** [haydenbbickerton/vue-charts#1]
Hey,

Awesome library, this isn't an issue but I wanted to get some advice before I contributed 

I was just wondering if you had any thoughts on handling 'select' events?

I am currently messing around with syncing a 'selected' prop between the parent and graph components, which works but it doesn't feel right. Another idea would be to dispatch an event but it could get messy if you have multiple graphs on the same page.

Cheers
Brock

**Comment by haydenbbickerton** [comment]
Sorry, what is it you're trying to do? 

If you're trying to change charts when the user selects something different in an dropdown/radio/input, [you can do something like this](https://haydenbbickerton.github.io/vue-charts/sets.html).

If you'd like to hook into the actual [select event](https://developers.google.com/chart/interactive/docs/events#the-select-event) from Google Charts itself, well, event functionality is in the next commit :)

**Comment by BrockReece** [comment]
Sorry for the ambiguity.

I was trying to hook into the select event from Google Charts. Since asking this though, I forked your project and made a small change that dispatches an event to the parent component when the Google Charts' select event is triggered.

Looks like you are a few steps ahead of me though :)

Thanks for your help.
Brock
