### ISSUE TITLE
Gauge Charts

### ISSUE THREAD

**Issue by Bodekaer** [haydenbbickerton/vue-charts#2]
Hi @haydenbbickerton,
Great initiative with VueCharts.

I tested it with the Gauge chart, but it throw an error: `google.load is not a function`
Any plans to support Gauge charts too?

**Comment by haydenbbickerton** [comment]
Thanks!

Gauge charts use the `gauge` package, did you pass that in using the `packages` prop?

Here's an example, adapted from [Googles Gauge Chart example](https://developers.google.com/chart/interactive/docs/gallery/gauge):

```
<vue-chart
    chart-type="Gauge"
    :packages="packages"
    :columns="columns"
    :rows="rows"
    :options="options"
></vue-chart>
```

And then in the Vue instance:
```javascript
data: function () {
  return {
    packages: ['gauge'],
    columns: [{
      'type': 'string',
      'label': 'Label'
    }, {
      'type': 'number',
      'label': 'Value'
    }],
    rows: [
      ['Memory', 80],
      ['CPU', 55],
      ['Network', 68]
    ],
    options: {
      width: 400,
      height: 120,
      redFrom: 90,
      redTo: 100,
      yellowFrom: 75,
      yellowTo: 90,
      minorTicks: 5
    }
  }
}
```

**Comment by Bodekaer** [comment]
Perfect! Thx so much @haydenbbickerton.
