### ISSUE TITLE
Google Charts loader.js can only be loaded once.

### ISSUE THREAD

**Issue by obonyojimmy** [haydenbbickerton/vue-charts#3]
Vue-charts throws error with latest vue version 1.0.20  `Google Charts loader.js can only be loaded once.` , kindly help , this was working before updated npm components

**Comment by haydenbbickerton** [comment]
Hey, thanks for bringing this to my attention! Just pushed v0.1.1, should be good now.

**Comment by bartoszmagier** [comment]
Hey @haydenbbickerton, I'm using `vue@2.2.1`, `vue-charts@0.2.1 ` and the problem is still present.
