### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '__eventTarget' of null

### ISSUE THREAD

**Issue by haleksandre** [haydenbbickerton/vue-charts#4]
When using some type of charts such as GeoChart, the events implementation is throwing the following error:

```
Uncaught (in promise) TypeError: Cannot read property '__eventTarget' of null
```

After troubleshooting, it seems that when the chart type is GeoChart the component's data `chart` doesn't get set before the `eventsBinder(self, self.chart, self.chartEvents)` gets called.

**Comment by haleksandre** [comment]
```
google.visualization.events.addOneTimeListener(self.wrapper, 'ready', function () {
     self.chart = self.wrapper.getChart();
});
```

It seems with GeoChart this listener gets trigger late

**Comment by haydenbbickerton** [comment]
Thanks for finding and debugging this! Just pushed a fix that should take care of this. Now it waits to bind events until the chart promise is resolved.

**Comment by rzb** [comment]
I'm getting the same error when binding a "select" event to a bar chart (material). I haven't tracked it down, but my first thought was that it might have something to do with loading data from remote? There's nothing to select when the component is mounted in this case.
