### ISSUE TITLE
No getSelection() function support?

### ISSUE THREAD

**Issue by lukpep** [haydenbbickerton/vue-charts#6]
Hi,

Is it possible to get currently selected item from vue-chart?
I try to use getSelection() from https://google-developers.appspot.com/chart/interactive/docs/reference#getselection

but it's not present on vue-chart object.

**Comment by haydenbbickerton** [comment]
Not right now, no. I talked in #5 about it's not exposing the chart object itself right now, but I intend to. Probably can put something together this weekend for that.

**Comment by lukpep** [comment]
@haydenbbickerton 
great news - thanks :)

**Comment by haydenbbickerton** [comment]
You know what, totally skipped my mind that you can get to the actual Google Chart object already. It's defined as `chart` in the component. So you can use something like the `$refs` functionality from vue to access to component directly.

Here's a quick example:
```
<vue-chart
    :columns="columns"
    :rows="rows"
    :options="options"
    v-ref:thisherechart
></vue-chart>
```

And then the Vue instance:
```javascript
var yoyo = new Vue({
  el: 'app',
  data: function () {
    ...
  })
})
```

Somewhere else in the code:
```javascript
// To call functions on the Google Chart object...
yoyo.$refs.thisherechart.chart.randomFunction();

// For example...
yoyo.$refs.thisherechart.chart.getSelection();
```

**Comment by lukpep** [comment]
I was going through vue-chart props in vue Devtools but chart object didnt catch my eye ;)
It works but once again i have problem with getting to vue data - methods or props from closures.
What i want to achive is to subscribe to select event of chart and get selected value.

I have method for getting selected data:

```
GetSelectedDate()
    {
      var selected = this.$refs.thisherechart.chart.getSelection();
      var data = this.rows[selected[0].row][0];
      console.log(data)
    },
```

and it works fine - for example when i bind it to button.

A also have working handler for selected event:

```
chartEvents: {
                    'select': function() {
                      console.log('selected from chart')
                    }
                },
```

Problem occurs when i try to put it together.
```
chartEvents: {
                    'select': function() {
                      this.GetSelectedDate();
                    }
                },
```

this is unknown in the scope of this function and i have no idea how to get arround it.

**Comment by haydenbbickerton** [comment]
Couple of options:

1. Use [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this). You'll have to transpile though, because es6 (which is awesome). This would be cleanest.
2.  You could use `data` as a getter and assign `this` to a variable. Something like this (untested) should work:
```javascript
get data () {
    var self = this;
    return {
        chartEvents: {
            'select': function() {
                self.GetSelectedDate();
            }
        }
    }
}
...
```

**Comment by lukpep** [comment]
option 2 worked fine for me - thank You :)
