### ISSUE TITLE
How to Update Chart Data

### ISSUE THREAD

**Issue by abigaleypc** [haydenbbickerton/vue-charts#7]

**Comment by haydenbbickerton** [comment]
Hi, I'd suggest you take a look at the [sets example](https://github.com/haydenbbickerton/vue-charts/blob/master/examples/sets.html). The chart will automatically update and redraw whenever the props are updated.

**Comment by haydenbbickerton** [comment]
Gonna take the thumbs up as a sign that that's what you were looking for :)
