### ISSUE TITLE
Manual Column Colors

### ISSUE THREAD

**Issue by CopyJosh** [haydenbbickerton/vue-charts#9]
How would someone go about incorporating custom colors on the bar graph in a similar manner to the google chart example? (link below).

The "colors" option array only works for "columns", where-as I need to be able to color rows. I know, it's a matter of semantics, but that's how the data is arranged.

`
columns: [
                {
                    'type': 'string',
                    'label': 'Products'
                },
                {
                    'type': 'number',
                    'label': 'Processing Costs ($)'
                }
            ],
            rows: [
['productOne', 10], ['productTwo', 20], ['productThree', 30] /* etc */
]
`

`
var data = google.visualization.arrayToDataTable([
         ['Element', 'Density', { role: 'style' }, { role: 'annotation' } ],
         ['Copper', 8.94, '#b87333', 'Cu' ],
         ['Silver', 10.49, 'silver', 'Ag' ],
         ['Gold', 19.30, 'gold', 'Au' ],
         ['Platinum', 21.45, 'color: #e5e4e2', 'Pt' ]
      ]);
`

https://developers.google.com/chart/interactive/docs/gallery/columnchart#coloring-columns

**Comment by haydenbbickerton** [comment]
Try this:
```javascript
columns: [{
    'type': 'string',
    'label': 'Products'
}, {
    'type': 'number',
    'label': 'Processing Costs ($)'
}, {
    'type': 'string',
    'role': 'style'
}],
rows: [
    ['Product One', 1000, 'silver'],
    ['Product Two', 1170, 'gold'],
    ['Product Three', 660,  'red'],
    ['Product Four', 1030, 'green']
],
```

[Here it is in jsFiddle](https://jsfiddle.net/0xg3xk8L/1/)

**Comment by CopyJosh** [comment]
Yes! Thank you, works great!
